/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileDescriptorCleaner */

#ifndef _Included_FileDescriptorCleaner
#define _Included_FileDescriptorCleaner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileDescriptorCleaner
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_FileDescriptorCleaner_clean
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
